#!/usr/bin/env bash
# Cases for .githooks/commit-msg, which CI also runs on every commit of a pull
# request. Both directions matter: a footer that slips through reaches public
# main, and a hook that rejects ordinary prose gets disabled.
set -uo pipefail
hook="$(dirname "${BASH_SOURCE[0]}")/../.githooks/commit-msg"
tmp="$(mktemp)"; trap 'rm -f "$tmp"' EXIT
pass=0; fail=0
t() {   # $1=name $2=message $3=accept|reject
  printf '%s\n' "$2" > "$tmp"
  local got=accept
  sh "$hook" "$tmp" >/dev/null 2>&1 || got=reject
  if [ "$got" = "$3" ]; then printf '  ok    %s\n' "$1"; pass=$((pass+1))
  else printf '  FAIL  %s: expected %s, got %s\n' "$1" "$3" "$got"; fail=$((fail+1)); fi
}
body=$'Fix the guard\n\nThe guard compared the wrong hash.'

t "an ordinary message"                     "$body"                                                        accept
t "prose about attribution mid-line"        "$body"$'\nWe strip Co-Authored-By: Claude lines in CI.'     accept
t "a human co-author"                       "$body"$'\n\nCo-Authored-By: Jane Doe <jane@example.org>'    accept
t "generated with care, in a sentence"      "$body"$'\nGenerated with care from the catalog.'            accept
t "Co-Authored-By naming Claude"            "$body"$'\n\nCo-Authored-By: Claude Opus <x@y>'               reject
t "Co-Authored-By, mixed case"              "$body"$'\n\nco-authored-by: CLAUDE <x@y>'                    reject
t "the anthropic noreply address"           "$body"$'\n\nCo-Authored-By: Someone <noreply@anthropic.com>' reject
t "a session line"                          "$body"$'\n\nClaude-Session: https://claude.ai/code/x'        reject
t "a bracketed Generated with footer"       "$body"$'\n\nGenerated with [Claude Code](https://x)'         reject
t "an unbracketed Generated with footer"    "$body"$'\n\nGenerated with Claude'                           reject
t "Generated by a tool"                     "$body"$'\n\ngenerated by Copilot'                             reject
t "the robot footer"                        "$body"$'\n\n🤖 Generated with something'                      reject
t "indented footer"                         "$body"$'\n\n   Co-Authored-By: Codex <x@y>'                  reject
t "tool name at the end of the line"        "$body"$'\n\nCo-Authored-By: Gemini'                          reject

printf '\n  %d ok, %d failed\n' "$pass" "$fail"
[ "$fail" = 0 ]
